# Generated by Django 6.0 on 2025-12-08 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("photoid", models.AutoField(primary_key=True, serialize=False)),
                ("photoDesc", models.TextField(blank=True, max_length=500, null=True)),
                ("photoFile", models.ImageField(upload_to="event_photos/")),
                ("uploadDate", models.DateTimeField(auto_now_add=True)),
                ("extractedTags", models.JSONField(blank=True, null=True)),
                (
                    "photoMeta",
                    models.JSONField(
                        blank=True,
                        help_text="EXIF, width, height, ai_labels, colors, model, iso, shutter_speed, gps, etc.",
                        null=True,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="events.events",
                    ),
                ),
                (
                    "uploadedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploadDate"],
                "indexes": [
                    models.Index(
                        fields=["event"], name="photos_phot_event_i_e40660_idx"
                    ),
                    models.Index(
                        fields=["uploadDate"], name="photos_phot_uploadD_96c072_idx"
                    ),
                ],
            },
        ),
    ]
