# Generated by Django 6.0 on 2025-12-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_comment_viewedphoto_downloadedphoto_likedphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="commentcount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="photo",
            name="downloadcount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="photo",
            name="likecount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="photo",
            name="viewcount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
