# Generated by Django 6.0 on 2025-12-10 14:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_photo_commentcount_photo_downloadcount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="viewedphoto",
            unique_together={("photo", "user")},
        ),
    ]
