# Generated by Django 5.2.9 on 2025-12-27 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0004_alter_viewedphoto_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="likedphoto",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
