# Generated by Django 5.2.9 on 2025-12-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0005_alter_likedphoto_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
