# Generated by Django 6.0 on 2025-12-08 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                ("eventid", models.AutoField(primary_key=True, serialize=False)),
                ("eventname", models.CharField(max_length=100)),
                ("eventdesc", models.TextField(max_length=1000)),
                ("eventdate", models.DateField()),
                ("eventtime", models.TimeField()),
                (
                    "eventCoverPhoto",
                    models.ImageField(
                        blank=True, default="", upload_to="event_covers/"
                    ),
                ),
                ("eventlocation", models.CharField(max_length=100)),
                (
                    "eventCreator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "events",
                "ordering": ["eventdate", "eventtime"],
            },
        ),
    ]
