# Generated by Django 6.0 on 2025-12-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="events",
            options={
                "ordering": ["eventdate", "eventtime"],
                "permissions": (
                    ("view_event_obj", "Can view this event object"),
                    ("change_event_obj", "Can change this event object"),
                    ("delete_event_obj", "Can delete this event object"),
                ),
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
    ]
