# Generated by Django 6.0 on 2025-12-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_events_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("img", "IMG Member"),
                    ("public", "Public"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
