# Generated by Django 5.2.9 on 2025-12-31 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_events_visibility"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="events",
            options={
                "ordering": ["eventdate", "eventtime"],
                "permissions": (
                    ("view_event_obj", "Can view this event object"),
                    ("change_event_obj", "Can change this event object"),
                    ("delete_event_obj", "Can delete this event object"),
                    ("invite_event_obj", "Can invite to this event object"),
                ),
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
    ]
