# Generated by Django 5.2.9 on 2025-12-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_events_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("img", "IMG Member"),
                    ("public", "Public"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
