# Generated by Django 5.2.9 on 2025-12-31 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_events_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("img", "IMG Member"),
                    ("public", "Public"),
                    ("private", "Private"),
                ],
                default="private",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="EventInvite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("viewer", "Viewer"), ("editor", "Editor")],
                        max_length=10,
                    ),
                ),
                ("token", models.UUIDField(unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.events"
                    ),
                ),
            ],
        ),
    ]
