# Generated by Django 5.2.9 on 2026-01-01 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_events_visibility_eventinvite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventinvite",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
