# Generated by Django 6.0 on 2025-12-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                ("userid", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150, unique=True)),
                (
                    "enrollmentNo",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "userProfile",
                    models.ImageField(
                        blank=True, null=True, upload_to="user_profiles/"
                    ),
                ),
                ("userbio", models.TextField(blank=True, max_length=500)),
                ("batch", models.IntegerField(blank=True, null=True)),
                ("dept", models.CharField(blank=True, max_length=100)),
                ("password", models.CharField(max_length=128)),
                ("token", models.CharField(blank=True, max_length=128, null=True)),
                ("roles", models.JSONField(blank=True, default=list)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["username"],
            },
        ),
    ]
