# Generated by Django 6.0 on 2025-12-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="token",
        ),
    ]
