# Generated by Django 6.0 on 2025-12-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_users_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="enrollmentNo",
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="userProfile",
            field=models.ImageField(blank=True, default="", upload_to="user_profiles/"),
        ),
        migrations.AlterField(
            model_name="users",
            name="userbio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
