# Generated by Django 6.0 on 2025-12-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_users_managers_users_first_name_users_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="roles",
        ),
    ]
