# Generated by Django 5.2.9 on 2025-12-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_emailotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
