# Generated by Django 5.2.9 on 2025-12-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_emailotp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="enrollmentNo",
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
